/* Generated By:JJTree: Do not edit this line. ASTDivNode.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=true,NODE_PREFIX=AST,NODE_EXTENDS=MyNode,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package cmm;

public
class ASTDivNode extends SimpleNode {
  public ASTDivNode(int id) {
    super(id);
  }

  public ASTDivNode(CMMParser p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=22c2da4f0ee66d2193f493a7c4d52100 (do not edit this line) */
