/* Generated By:JJTree: Do not edit this line. ASTDeclaration.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=true,NODE_PREFIX=AST,NODE_EXTENDS=MyNode,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package cmm;

public
class ASTDeclaration extends SimpleNode implements CMMParserConstants{
	public int type;
	public String name;
	
  public ASTDeclaration(int id) {
    super(id);
  }

  public ASTDeclaration(CMMParser p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=528623a144fdd08038a099d667a0a9b3 (do not edit this line) */
