/* Generated By:JJTree: Do not edit this line. ASTFormId.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=true,NODE_PREFIX=AST,NODE_EXTENDS=MyNode,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package cmm;

public
class ASTFormId extends SimpleNode {
	String name;
	int index;
  public ASTFormId(int id) {
    super(id);
  }

  public ASTFormId(CMMParser p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=010d66d2e9fb3dd25daa4415ed62d5a1 (do not edit this line) */
