/* Generated By:JJTree: Do not edit this line. ASTGENode.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=true,NODE_PREFIX=AST,NODE_EXTENDS=MyNode,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package cmm;

public
class ASTGENode extends SimpleNode {
  public ASTGENode(int id) {
    super(id);
  }

  public ASTGENode(CMMParser p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=3aefd5517d198d57d5c17d803e21da2c (do not edit this line) */
