/* Generated By:JJTree: Do not edit this line. ASTIntConstNode.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=true,NODE_PREFIX=AST,NODE_EXTENDS=MyNode,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package cmm;

public
class ASTIntConstNode extends SimpleNode {
  int val;
  public ASTIntConstNode(int id) {
    super(id);
  }

  public ASTIntConstNode(CMMParser p, int id) {
    super(p, id);
  }

  public void interpret()
  {
    stack[++top] = new Integer(val);
  }
}
/* JavaCC - OriginalChecksum=ba03f8b46838d2cfad4d337cd89a23fb (do not edit this line) */
