/* Generated By:JJTree: Do not edit this line. ASTId.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=true,NODE_PREFIX=AST,NODE_EXTENDS=MyNode,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package cmm;

public
class ASTId extends SimpleNode {
	 String name;
	 
  public ASTId(int id) {
	 
    super(id);
  }

  public ASTId(CMMParser p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=9d817b6743d659c23914f7d3b0b39c23 (do not edit this line) */
