/* Generated By:JJTree: Do not edit this line. ASTIfStmt.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=true,NODE_PREFIX=AST,NODE_EXTENDS=MyNode,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package cmm;

public
class ASTIfStmt extends SimpleNode {
  public ASTIfStmt(int id) {
    super(id);
  }

  public ASTIfStmt(CMMParser p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=1199591a919c85ad6f8d35849b72be30 (do not edit this line) */
