/* Generated By:JJTree: Do not edit this line. ASTLTNode.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=true,NODE_PREFIX=AST,NODE_EXTENDS=MyNode,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package cmm;

public
class ASTLTNode extends SimpleNode {
  public ASTLTNode(int id) {
    super(id);
  }

  public ASTLTNode(CMMParser p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=c48284dbf6fd41e3dfa22caf9e8bbea4 (do not edit this line) */
