/* Generated By:JJTree: Do not edit this line. ASTMulNode.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=true,NODE_PREFIX=AST,NODE_EXTENDS=MyNode,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package cmm;

public
class ASTMulNode extends SimpleNode {
  public ASTMulNode(int id) {
    super(id);
  }

  public ASTMulNode(CMMParser p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=32b5f12513b9e27cadbe3c02f5817fb3 (do not edit this line) */
