/* Generated By:JJTree: Do not edit this line. ASTNENode.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=true,NODE_PREFIX=AST,NODE_EXTENDS=MyNode,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package cmm;

public
class ASTNENode extends SimpleNode {
  public ASTNENode(int id) {
    super(id);
  }

  public ASTNENode(CMMParser p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=f8f439f6c7b648590b9bd6d75e048c6f (do not edit this line) */
