/* Generated By:JJTree: Do not edit this line. ASTProcedure.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=true,NODE_PREFIX=AST,NODE_EXTENDS=MyNode,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package cmm;

public
class ASTProcedure extends SimpleNode {
  public ASTProcedure(int id) {
    super(id);
  }

  public ASTProcedure(CMMParser p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=6c1865d3a146226cd665866b30f76107 (do not edit this line) */
