/* Generated By:JJTree: Do not edit this line. ASTReadStmt.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=true,NODE_PREFIX=AST,NODE_EXTENDS=MyNode,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package cmm;

public
class ASTReadStmt extends SimpleNode {
  public ASTReadStmt(int id) {
    super(id);
  }

  public ASTReadStmt(CMMParser p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=cf509c1bc32cc86b81296a7c0a11785e (do not edit this line) */
