/* Generated By:JJTree: Do not edit this line. ASTScalarDeclaration.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=true,NODE_PREFIX=AST,NODE_EXTENDS=MyNode,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package cmm;

public
class ASTScalarDeclaration extends SimpleNode implements CMMParserConstants{
	public int type;
	public String name;
	
  public ASTScalarDeclaration(int id) {
    super(id);
  }

  public ASTScalarDeclaration(CMMParser p, int id) {
    super(p, id);
  }

  public void putInTable() {
	  if (type == INT) {
		  symtab.put(name, new Integer(0));
	  }else if(type == REAL) {
		  symtab.put(name, new Double(0));
	  }
  }
}
/* JavaCC - OriginalChecksum=054b53d5f40d98a35f628ac3f9e573f3 (do not edit this line) */
