/* Generated By:JJTree: Do not edit this line. ASTScalarId.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=true,NODE_PREFIX=AST,NODE_EXTENDS=MyNode,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package cmm;

public
class ASTScalarId extends SimpleNode {
	String name;
  public ASTScalarId(int id) {
    super(id);
  }

  public ASTScalarId(CMMParser p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=35a6bb9d642be5bc4818c799d713a16e (do not edit this line) */
