/* Generated By:JJTree: Do not edit this line. ASTSubNode.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=true,NODE_PREFIX=AST,NODE_EXTENDS=MyNode,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package cmm;

public
class ASTSubNode extends SimpleNode {
  public ASTSubNode(int id) {
    super(id);
  }

  public ASTSubNode(CMMParser p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=3a8530a10f7cdece9877df1a66b92844 (do not edit this line) */
