/* Generated By:JJTree: Do not edit this line. ASTTerm.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=true,NODE_PREFIX=AST,NODE_EXTENDS=MyNode,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package cmm;

public
class ASTTerm extends SimpleNode {
  public ASTTerm(int id) {
    super(id);
  }

  public ASTTerm(CMMParser p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=026cffe775d533d39a9909c23e1aa148 (do not edit this line) */
