/* Generated By:JJTree: Do not edit this line. ASTWhileStmt.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=true,NODE_PREFIX=AST,NODE_EXTENDS=MyNode,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package cmm;

public
class ASTWhileStmt extends SimpleNode {
  public ASTWhileStmt(int id) {
    super(id);
  }

  public ASTWhileStmt(CMMParser p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=43ecf6d8a2057ae66ffeaf77e15bcc80 (do not edit this line) */
