/* Generated By:JJTree: Do not edit this line. ASTWriteStmt.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=true,NODE_PREFIX=AST,NODE_EXTENDS=MyNode,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package cmm;

public
class ASTWriteStmt extends SimpleNode {
  public ASTWriteStmt(int id) {
    super(id);
  }

  public ASTWriteStmt(CMMParser p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=727349f8e4990255bede6c291a588c7f (do not edit this line) */
