/* Generated By:JavaCC: Do not edit this line. CMMParserTreeConstants.java Version 5.0 */
package cmm;

public interface CMMParserTreeConstants
{
  public int JJTSTART = 0;
  public int JJTVOID = 1;
  public int JJTBLOCK = 2;
  public int JJTWHILESTMT = 3;
  public int JJTREADSTMT = 4;
  public int JJTWRITESTMT = 5;
  public int JJTIFSTMT = 6;
  public int JJTEQNODE = 7;
  public int JJTNENODE = 8;
  public int JJTLTNODE = 9;
  public int JJTGTNODE = 10;
  public int JJTLENODE = 11;
  public int JJTGENODE = 12;
  public int JJTSCALARDECLARATION = 13;
  public int JJTFORMDECLARATION = 14;
  public int JJTASSIGNMENT = 15;
  public int JJTADDNODE = 16;
  public int JJTSUBNODE = 17;
  public int JJTMULNODE = 18;
  public int JJTDIVNODE = 19;
  public int JJTSCALARID = 20;
  public int JJTFORMID = 21;
  public int JJTINTCONSTNODE = 22;
  public int JJTREALCONSTNODE = 23;


  public String[] jjtNodeName = {
    "Start",
    "void",
    "Block",
    "WhileStmt",
    "ReadStmt",
    "WriteStmt",
    "IfStmt",
    "EQNode",
    "NENode",
    "LTNode",
    "GTNode",
    "LENode",
    "GENode",
    "ScalarDeclaration",
    "FormDeclaration",
    "Assignment",
    "AddNode",
    "SubNode",
    "MulNode",
    "DivNode",
    "ScalarId",
    "FormId",
    "IntConstNode",
    "RealConstNode",
  };
}
/* JavaCC - OriginalChecksum=dfe325dcea4714833ce8c8f8ceb23d6b (do not edit this line) */
